//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentSchedule_History
    {
        public int Id { get; set; }
        public System.Guid TransactionId { get; set; }
        public System.Guid WebsiteKey { get; set; }
        public string PayerKey { get; set; }
        public System.DateTime DateOfService { get; set; }
        public Nullable<int> ScriptFinished { get; set; }
        public Nullable<System.DateTime> LastRun { get; set; }
        public Nullable<int> ScheduleType { get; set; }
        public Nullable<int> MaxTries { get; set; }
        public Nullable<int> NumTries { get; set; }
        public Nullable<System.DateTime> NextRun { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<System.DateTime> ArchiveDate { get; set; }
    }
}
