//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentTransactionRespons
    {
        public int Id { get; set; }
        public System.Guid TransactionId { get; set; }
        public string RawAgentResponse { get; set; }
        public Nullable<int> ScriptRunId { get; set; }
        public Nullable<int> ExtractionResultId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsProcessed { get; set; }
    }
}
