//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authorization
    {
        public int RecordId { get; set; }
        public int Encounters_RecordId { get; set; }
        public string AuthNumber { get; set; }
        public string PayerId { get; set; }
        public string ReferralStatus { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string CPTs { get; set; }
        public string Diagnoses { get; set; }
        public Nullable<int> Visits { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> DateOfChange { get; set; }
    
        public virtual Encounter Encounter { get; set; }
    }
}
