//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientScript
    {
        public int Id { get; set; }
        public Nullable<System.Guid> CriteriaSetKey { get; set; }
        public string criteriaSetName { get; set; }
        public Nullable<System.Guid> ClientKey { get; set; }
        public Nullable<System.Guid> ClientLocationKey { get; set; }
        public string PayerKey { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public Nullable<System.Guid> InitialScriptId { get; set; }
        public Nullable<bool> UseRBM { get; set; }
    }
}
