//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CriteriaSet
    {
        public System.Guid CriteriaSetKey { get; set; }
        public string CriteriaSetName { get; set; }
        public System.Guid StartingScriptKey { get; set; }
        public string DeviceId { get; set; }
    }
}
