//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dsa_agentRequestQueue_History
    {
        public System.Guid transactionID { get; set; }
        public Nullable<long> transactionTimeStamp { get; set; }
        public Nullable<long> appRequestTimeStamp { get; set; }
        public Nullable<System.Guid> sessionToken { get; set; }
        public Nullable<System.Guid> appKey { get; set; }
        public System.Guid clientKey { get; set; }
        public System.Guid clientLocKey { get; set; }
        public string mappingCriteria { get; set; }
        public string requestPayloadType { get; set; }
        public string rawPayload { get; set; }
        public Nullable<bool> responseReady { get; set; }
        public Nullable<long> responseReadyTimeStamp { get; set; }
        public string rawWorkloadResponse { get; set; }
        public int currentState { get; set; }
        public bool NoPrompt { get; set; }
        public string AgentWorkPayload { get; set; }
        public Nullable<System.DateTime> ArchiveDate { get; set; }
    }
}
