//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dsa_AutoRerun
    {
        public System.Guid TransactionID { get; set; }
        public string PCKEY { get; set; }
        public int Interval { get; set; }
        public System.DateTime dateAdded { get; set; }
        public System.DateTime LastRun { get; set; }
        public string EntKey { get; set; }
        public Nullable<System.Guid> NewTransactionID { get; set; }
        public Nullable<int> EncounterQueueRecordKey { get; set; }
        public short CurrentState { get; set; }
        public int MaxRetries { get; set; }
        public int Attempts { get; set; }
        public bool BatchMode { get; set; }
        public string IPR_HAI_KEY { get; set; }
    }
}
