//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dsa_criteriaSets
    {
        public Nullable<System.DateTime> dateAdded { get; set; }
        public Nullable<System.DateTime> dateChanged { get; set; }
        public string lastUserID { get; set; }
        public string deviceID { get; set; }
        public System.Guid criteriaSetKey { get; set; }
        public string criteriaSetName { get; set; }
        public Nullable<System.Guid> transactionTypeKey { get; set; }
        public Nullable<System.Guid> scriptKey { get; set; }
        public int irecordKey { get; set; }
        public int Priority { get; set; }
    }
}
