//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dsa_clientLocations
    {
        public dsa_clientLocations()
        {
            this.PortalUsers = new HashSet<PortalUser>();
        }
    
        public int id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public Nullable<System.DateTime> dateAdded { get; set; }
        public Nullable<System.DateTime> dateChanged { get; set; }
        public string lastUserID { get; set; }
        public string deviceID { get; set; }
        public string clientLocationName { get; set; }
        public System.Guid clientKey { get; set; }
        public System.Guid clientLocationKey { get; set; }
        public string locationAddress { get; set; }
        public string locationAddress2 { get; set; }
        public string locationCity { get; set; }
        public string locationState { get; set; }
        public string locationZip { get; set; }
        public string locationPhone { get; set; }
        public string locationFax { get; set; }
        public string locationContactName { get; set; }
        public string locationContacteMail { get; set; }
        public string locationContactPhone { get; set; }
        public string locationContactPhoneType { get; set; }
        public int irecordKey { get; set; }
        public string locationServerAlias { get; set; }
        public string locationDB { get; set; }
        public string clientId { get; set; }
        public string tpid { get; set; }
        public string facilityId { get; set; }
    
        public virtual ICollection<PortalUser> PortalUsers { get; set; }
    }
}
