//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dsa_websiteExtractionMapping
    {
        public int RecKey { get; set; }
        public System.Guid ExtractKey { get; set; }
        public System.Guid WebsiteKey { get; set; }
        public string DataName { get; set; }
        public string DocumentLocation { get; set; }
        public string LocationType { get; set; }
        public string LocationValue { get; set; }
        public string FormatFunction { get; set; }
        public string ValueFunction { get; set; }
        public Nullable<int> Priority { get; set; }
    }
}
