//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dsa_portalList
    {
        public string siteName { get; set; }
        public Nullable<System.Guid> WebsiteKeyInquiry { get; set; }
        public Nullable<System.Guid> WebsiteKeySubmit { get; set; }
        public Nullable<System.Guid> InitialInquiryScriptKey { get; set; }
        public Nullable<System.Guid> InitialSubmitScriptKey { get; set; }
        public int RecKey { get; set; }
    }
}
