//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dsa_facilityMaster
    {
        public int RecordKey { get; set; }
        public System.Guid FacilityKey { get; set; }
        public string FacilityName { get; set; }
        public string OrderMap { get; set; }
        public string FacilityAddress { get; set; }
        public string FacilityAddress2 { get; set; }
        public string FacilityCity { get; set; }
        public string FacilityState { get; set; }
        public string FacilityZip { get; set; }
        public string FacilityTelephone { get; set; }
        public string FacilityFax { get; set; }
        public string ClientKey { get; set; }
        public string ClientLocationKey { get; set; }
    }
}
