//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dsa_scriptCollectionItems
    {
        public Nullable<System.DateTime> dateAdded { get; set; }
        public Nullable<System.DateTime> dateChanged { get; set; }
        public string lastUserID { get; set; }
        public string deviceID { get; set; }
        public System.Guid scriptKey { get; set; }
        public System.Guid fieldKey { get; set; }
        public Nullable<System.Guid> scriptID { get; set; }
        public string overrideLabel { get; set; }
        public string defaultValue { get; set; }
        public string valueValidation { get; set; }
        public bool required { get; set; }
        public string collectionMask { get; set; }
        public string validationRoutine { get; set; }
        public bool Can_Go_Back { get; set; }
    }
}
