//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dsa_clientLocations_test
    {
        public int id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public Nullable<System.DateTime> dateAdded { get; set; }
        public Nullable<System.DateTime> dateChanged { get; set; }
        public string lastUserID { get; set; }
        public string deviceID { get; set; }
        public string clientLocationName { get; set; }
        public System.Guid clientKey { get; set; }
        public System.Guid clientLocationKey { get; set; }
        public string clientID { get; set; }
        public string tpid { get; set; }
        public string facilityID { get; set; }
        public Nullable<bool> downloadFile { get; set; }
    }
}
