//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dsa_responseFormats
    {
        public Nullable<System.DateTime> dateAdded { get; set; }
        public Nullable<System.DateTime> dateChanged { get; set; }
        public string lastUserID { get; set; }
        public string deviceID { get; set; }
        public System.Guid responseFormatKey { get; set; }
        public System.Guid clientLocKey { get; set; }
        public System.Guid appKey { get; set; }
        public string formatGenerator { get; set; }
        public string parameterString { get; set; }
        public string formatDescription { get; set; }
        public Nullable<int> irecordKey { get; set; }
        public string formatTemplate { get; set; }
    }
}
