//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dsa_userLogins
    {
        public Nullable<System.DateTime> dateAdded { get; set; }
        public Nullable<System.DateTime> dateChanged { get; set; }
        public string lastUserID { get; set; }
        public string deviceID { get; set; }
        public System.Guid clientKey { get; set; }
        public System.Guid clientLocationKey { get; set; }
        public string userID { get; set; }
        public System.Guid websiteKey { get; set; }
        public string websiteUsername { get; set; }
        public string websitePassword { get; set; }
        public string websiteAddon1 { get; set; }
        public string websiteAddon2 { get; set; }
        public Nullable<System.Guid> websiteRenewalKey { get; set; }
        public Nullable<int> userLevel { get; set; }
        public System.Guid recordKey { get; set; }
    }
}
