//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dsa_fieldMaster
    {
        public Nullable<System.DateTime> dateAdded { get; set; }
        public Nullable<System.DateTime> dateChanged { get; set; }
        public string lastUserID { get; set; }
        public string deviceID { get; set; }
        public System.Guid fieldKey { get; set; }
        public string fieldLabel { get; set; }
        public string fieldType { get; set; }
        public Nullable<short> fieldMaxLen { get; set; }
        public Nullable<short> fieldMinLen { get; set; }
        public string fieldCollectionMask { get; set; }
        public string fieldValidationRoutine { get; set; }
        public string fieldName { get; set; }
        public short fieldSize { get; set; }
        public bool fieldRequired { get; set; }
        public bool useListbox { get; set; }
        public bool useClientSpecificList { get; set; }
        public int irecordKey { get; set; }
    }
}
