//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dsa_websiteMappingValues
    {
        public System.Guid recordKey { get; set; }
        public Nullable<System.DateTime> dateAdded { get; set; }
        public Nullable<System.DateTime> dateChanged { get; set; }
        public string lastUserID { get; set; }
        public string deviceID { get; set; }
        public System.Guid websiteKey { get; set; }
        public System.Guid fieldKey { get; set; }
        public string fieldValue { get; set; }
        public int irecordKey { get; set; }
        public string NormalizedValue { get; set; }
        public string Priority { get; set; }
    }
}
