//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dsa_facilityDetails
    {
        public string DetailLabel { get; set; }
        public string DetailValue { get; set; }
        public System.Guid FacilityKey { get; set; }
        public System.Guid DetailKey { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public int RecordKey { get; set; }
    }
}
