//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dsa_AutoRerunCompleted
    {
        public System.Guid TrasactionID { get; set; }
        public string PCKEY { get; set; }
        public System.DateTime DateCompleted { get; set; }
    }
}
