//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dsa_PayerWebsiteMappingValues
    {
        public int RecordKey { get; set; }
        public string Primary_PayerKey { get; set; }
        public string WebSiteKey { get; set; }
        public string DefaultValue { get; set; }
        public string ClientKey { get; set; }
        public string ClientLocationKey { get; set; }
        public string DetailLabel { get; set; }
    }
}
