//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encounter
    {
        public Encounter()
        {
            this.Authorizations = new HashSet<Authorization>();
        }
    
        public int RecordId { get; set; }
        public string EncounterId { get; set; }
        public int WorkFlowStatusId { get; set; }
        public string MRN { get; set; }
        public string Username { get; set; }
        public Nullable<System.Guid> TransactionId { get; set; }
        public string AuthNumber { get; set; }
        public string TradingPartnerId { get; set; }
        public string ClientId { get; set; }
        public string FacilityId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual ICollection<Authorization> Authorizations { get; set; }
    }
}
