//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtractionAuthProcedure
    {
        public int ProcedureId { get; set; }
        public Nullable<int> ExtractionAuthId { get; set; }
        public string CPT { get; set; }
        public string Description { get; set; }
    
        public virtual ExtractionAuth ExtractionAuth { get; set; }
    }
}
