//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtractionAuthImage
    {
        public int ExtractionAuthId { get; set; }
        public byte[] PNG { get; set; }
        public string ExternalMongoId { get; set; }
    }
}
