//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtractionResult
    {
        public ExtractionResult()
        {
            this.ExtractionAuths = new HashSet<ExtractionAuth>();
            this.FilteredPrecerts = new HashSet<FilteredPrecert>();
        }
    
        public int Id { get; set; }
        public System.Guid TransactionId { get; set; }
        public string ExtractedValues { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
    
        public virtual ICollection<ExtractionAuth> ExtractionAuths { get; set; }
        public virtual ICollection<FilteredPrecert> FilteredPrecerts { get; set; }
    }
}
