//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilteredPrecert
    {
        public int FilteredPrecertId { get; set; }
        public Nullable<int> ExtractionResultId { get; set; }
        public Nullable<int> ExtractionAuthId { get; set; }
        public Nullable<bool> ScriptFinished { get; set; }
        public string AuthNumber { get; set; }
        public string ServiceCode { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string Procedures { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    
        public virtual ExtractionAuth ExtractionAuth { get; set; }
        public virtual ExtractionResult ExtractionResult { get; set; }
    }
}
