//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NormalizedStatus
    {
        public int Id { get; set; }
        public string NormalizedStatusEnum { get; set; }
        public Nullable<bool> IsDeliverableStatus { get; set; }
        public Nullable<bool> IsRescheduleStatus { get; set; }
        public string ExternalFacingStatus { get; set; }
        public Nullable<bool> SendImage { get; set; }
    }
}
