//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnDemandCredential
    {
        public int Id { get; set; }
        public Nullable<System.Guid> TransactionId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<bool> IsPersisted { get; set; }
        public string ClientId { get; set; }
        public string TradingPartnerId { get; set; }
        public string FacilityId { get; set; }
        public string IPRKey { get; set; }
    }
}
