//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayerRouting
    {
        public int RBMRoutingId { get; set; }
        public bool isActive { get; set; }
        public string PayerIdentifier { get; set; }
        public string FieldName { get; set; }
        public string Criteria { get; set; }
        public System.DateTime DateAdded { get; set; }
        public System.Guid ClientKey { get; set; }
        public System.Guid ClientLocKey { get; set; }
    }
}
