//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RqaAlertConfiguration
    {
        public int Id { get; set; }
        public string AuthStatusType { get; set; }
        public string AlertType { get; set; }
        public string AlertText { get; set; }
    }
}
