//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAClientVersion
    {
        public int Id { get; set; }
        public System.DateTime UpdatedVersionOn { get; set; }
        public string ClientId { get; set; }
        public int VersionNumber { get; set; }
        public string ErrorMessage { get; set; }
        public string ActionType { get; set; }
    }
}
