//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScriptRuns_History
    {
        public int Id { get; set; }
        public System.Guid TransactionId { get; set; }
        public System.DateTimeOffset RunDate { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> WebsiteKey { get; set; }
        public string ClientId { get; set; }
        public string TradingPartnerId { get; set; }
        public string WebsiteUser { get; set; }
        public string FacilityId { get; set; }
        public string IPRKey { get; set; }
        public string AgentIdentifier { get; set; }
        public Nullable<int> WebsiteUserMasterId { get; set; }
        public Nullable<int> PortalUser_Id { get; set; }
        public Nullable<System.DateTime> ScriptRunFinished { get; set; }
        public Nullable<System.DateTime> ArchiveDate { get; set; }
    }
}
