//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusNormalization
    {
        public int Id { get; set; }
        public string StatusText { get; set; }
        public string NormalizedStatus { get; set; }
        public string AuthReason { get; set; }
        public Nullable<System.Guid> websiteKey { get; set; }
        public Nullable<System.Guid> transactionId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
