//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionResult
    {
        public int Id { get; set; }
        public Nullable<System.Guid> transactionId { get; set; }
        public string precertNumber { get; set; }
        public string normalizedStatus { get; set; }
        public string originalStatus { get; set; }
        public Nullable<System.DateTime> effectiveDate { get; set; }
        public Nullable<System.DateTime> expirationDate { get; set; }
        public Nullable<System.DateTimeOffset> dateAdded { get; set; }
        public byte[] pngData { get; set; }
    }
}
