//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TXFiling
    {
        public int RecordKey { get; set; }
        public System.Guid TransactionID { get; set; }
        public string UPWUser { get; set; }
        public string EntKey { get; set; }
        public string PatKey { get; set; }
        public string PatEncounterID { get; set; }
        public int InquiryOrSubmit { get; set; }
        public string PayerKey { get; set; }
        public Nullable<System.Guid> OrderKey { get; set; }
        public string InsInf { get; set; }
        public Nullable<System.DateTime> Add_Date { get; set; }
        public Nullable<System.DateTime> Completed_Date { get; set; }
        public bool Completed { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> Create_Timestamp { get; set; }
    }
}
