//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAgentTool.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteUserMaster
    {
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string ParentName { get; set; }
        public System.Guid ClientKey { get; set; }
        public System.Guid ClientLocationKey { get; set; }
        public System.Guid WebsiteKey { get; set; }
        public bool IgnoreWebsiteKey { get; set; }
        public string WebsiteUsername { get; set; }
        public string WebsitePassword { get; set; }
        public Nullable<int> UserLevel { get; set; }
        public string WebsiteDescription { get; set; }
        public Nullable<int> PortalId { get; set; }
    }
}
